
import sam from '../assets/sam.jpeg'
import sebMessage from '../assets/sebMessage.jpeg'
import toyin from '../assets/toyinn.jpeg'
import wounded from '../assets/cb1c6c230ce21bf2.jpg'
import abraham from '../assets/abraham.jpeg'
import kid from '../assets/kid.jpeg'

import koi from '../assets/koi.jpeg'
import rela from '../assets/rela.jpeg'
import issue from '../assets/issue1.jpg'
import vd1 from '../assets/3700e6d86669441f.mp4'
import vd2 from '../assets/3480cf6ea72b7c47.mp4'
import vd3 from '../assets/27e6c97320d6c59e.mp4'
import scholar from '../assets/scholar.mp4'
import jude from '../assets/jude.jpg'
import money from '../assets/money.mp4'
import nofight from '../assets/nofight.mp4'
import period from '../assets/period.mp4'
import homeland from '../assets/homeland.jpeg'

export const data = [
  {
    id: '1',
    type:"video",
    image_url:jude,
    iconName: 'location-pin',
    intro:'Hi, I am here to help you build your health,and nurture your entire well-being',
    category:'H',
    poster_img:homeland,
    poster:'Mike&Her',
    follower:'240',
    following:'160',
    posts:'1',
    title:'Family | Relationship | Health',
    post_title:'if only we understood',
    post_desc:'Understanding your sex drive, hormones and other related ...',
    post_date:'3 days ago',
    post_like:'12',
    post_relate:'4',
    video:period
  },
  {
    id: '2',
    type:"img",
    image_url:jude,
    iconName: 'location-pin',
    intro:'Hello, I am here to help strengthen bonds with families, create lasting memories, and foster a nurturing and supportive home environment',
    category:'M',
    poster_img:toyin,
    title:'Finance | Health | Good News',
    follower:'710',
    following:'300',
    posts:'2',
    poster:'Liquidsoul',
    post_title:'if only we understood',
    post_desc:'This is where we all have to agree that in relationship, we have to exercise what i call the 3 MAIN RECIPIES. First is communication',
    post_date:'3 days ago',
    post_like:'12',
    post_relate:'4',
    video:vd1
  },
  {
    id: '3',
    muteId:'2',
    type:"video",
    category:'F',
    image_url:issue,
    intro:'Hello everyone, I am here to help build financial empowerment, build wealth, and achieve financial well-being',
    iconName: 'location-pin',
    poster_img:sam,
    poster:'Scholar',
    title:'Finance | Moltivation | Relationship',
    follower:'680',
    following:'210',
    posts:'3',
    post_title:'Lets make live easy',
    post_desc:'Dont allow people to gult stripe you for not giving. We must understand the principles around giving so that we dont give in error',
    post_date:'3 days ago',
    post_like:'12',
    post_relate:'4',
    video:money
  },
  {
    id: '4',
    muteId:'4',
    type:"video",
    category:'R',
    image_url:issue,
    iconName: 'location-pin',
    intro:'Hello everyone, I am here to help build financial empowerment, build wealth, and achieve financial well-being',
    poster_img:sam,
    poster:'Scholar',
    title:'Finance | Moltivation | Relationship',
    follower:'680',
    following:'210',
    posts:'3',
    post_title:'Lets make live easy',
    post_desc:'Learning the act of forgiveness,and always respect yourselves',
    post_date:'3 days ago',
    post_like:'12',
    post_relate:'4',
    video:nofight
  },
  {
    id: '5',
    muteId:'5',
    type:"video",
    category:'G',
    image_url:issue,
    iconName: 'location-pin',
    poster_img:sam,
    poster:'Scholar',
    title:'Finance | Moltivation | Relationship',
    follower:'680',
    following:'210',
    posts:'3',
    intro:'Hello everyone, I am here to help build financial empowerment, build wealth, and achieve financial well-being',
    post_title:'Lets make live easy',
    post_desc:'Dont make someone elses life difficult because Allah will make your life difficult',
    post_date:'3 days ago',
    post_like:'12',
    post_relate:'4',
    video:scholar
  },
    {
      id: '6',
      type:"video",
      muteId:'6',
      category:'M',
      image_url:issue,
      iconName: 'location-pin',
      poster_img:wounded,
      poster:'Wounded_Healer',
      title:'Career | Moltivation | Health',
      follower:'107',
      following:'603',
      posts:'2',
      intro:'Hi, I am here to build meaningful connections, nurture a loving relationship, and create a foundation of trust and understanding.',
      post_title:'Rejections made me stronger',
      post_desc:'There is a time coming in your life in the near near near...',
      post_date:'3 days ago',
      post_like:'12',
      post_relate:'4',
      video:vd1
    },
    {
      id: '7',
      type:"img",
      image_url:issue,
      category:'R',
      iconName: 'location-pin',
      intro:'Hello, I am here to help strengthen bonds with families, create lasting memories, and foster a nurturing and supportive home environment',
      poster_img:toyin,
      poster:'Liquidsoul',
      title:'Finance | Health | Good News',
      follower:'710',
      following:'300',
      posts:'2',
      post_title:'if only we understood',
      post_desc:'This is where we all have to agree that in relationship, we have to exercise what i call the 3 MAIN RECIPIES. First is communication',
      post_date:'3 days ago',
      post_like:'12',
      post_relate:'4',
      video:vd1
    },
    {
      id: '8',
      type:"img",
      image_url:sebMessage,
      category:'G',
      follower:'459',
      posts:'2',
      following:'290',
      title:'Family | Good News | Moltivation | Relationship',
      iconName: 'location-pin',
      intro:'Hi, I am here to embrace the teachings of the Good news, seek spiritual enlightenment, and live a life guided by faith and compassion.',
      poster_img:abraham,
      poster:'Gnexdor',
      post_title:'Dont Give up',
      post_desc:'Your never giving up altitude will, make your enemies give up on you. A story was once told about a your man from Ogwashi-uku village in Delta state',
      post_date:'4 days ago',
      post_like:'3',
      post_relate:'2.1',
   
    },
    {
      id: '9',
      type:"video",
      muteId:'5',
      category:'M',
      // image_url:greater,
      poster_img:kid,
      title:'Health | Family | Relationship',
      follower:'601',
      following:'393',
      posts:'2',
      poster:'FaithIt',
      intro:'Hi, I am here to learn, grow and Heal',
      post_title:'The way to greatness',
      post_desc:'Lets encourage men to speak up and not man up. Speaking up saves lives',
      post_date:'a week ago',
      post_like:'6',
      post_relate:'1.4',
      sub:'Subscribe',
      video:vd2
    }, 
    {
      id: '10',
      type:"img",
      image_url:koi,
      category:'G',
      title:'Health | Family | Relationship',
      follower:'601',
      following:'393',
      posts:'2',
      iconName: 'location-pin',
      intro:'Hi, I am here to learn, grow and Heal',
      poster_img:kid,
      poster:'FaithIt',
      post_title:'All blessing is from God',
      post_desc:'All blessings are from God through men to men. woe betides a man who looks unto man as his helper',
      post_date:'4 days ago',
      post_like:'9',
      post_relate:'7',
   
    },
    {
      id: '11',
      type:"video",
      muteId:'7',
      category:'G',
      intro:'Hi, I am here to embrace the teachings of the Good news, seek spiritual enlightenment, and live a life guided by faith and compassion.',
      follower:'459',
      posts:'2',
      following:'290',
      title:'Family | Good News | Moltivation | Relationship',
      poster_img:abraham,
      poster:'Gnexdor',
      post_title:'All blessing comes from God, through men',
      post_desc:'Trust in the lord with all your heart, lean not in your undestanding ..',
      post_date:'2 weeks ago',
      post_like:'13.2',
      post_relate:'8',
      video:vd3
    }, 
    {
      id: '12',
      type:"img",
      category:'R',
      image_url:rela,
      poster_img:wounded,
      title:'Career | Moltivation | Health',
      follower:'107',
      following:'603',
      posts:'2',
      intro:'Hi, I am here to build meaningful connections, nurture a loving relationship, and create a foundation of trust and understanding.',
      poster:'Wounded_Healer',
      post_title:'One right person is enough',
      post_desc:'The a world where everybody is living a fast life. selfishness and self-centeredness is the order of the day. it sad but its important we know the bitter truth or the reality of our time.',
      post_date:'3 weeks ago',
      post_like:'2.3',
      post_relate:'3.4',
    }, 
  ];
  