export const data = 

[{"id": 1,
 "idd": 1,
 "type": "HOSPITAL 1",
  "option": "hospital",
  "name": "1 month", 
  "price_increment": "5.00"},
  {"id": 2,
  "idd": 2, 
  "type": "HOSPITAL 2",
  "option": "hospital",
  "name": "2 months",
  "price_increment": "10.00"},
   {"id": 3, 
   "idd": 3,
   "type": "HOSPITAL 3",
   "name": "> 2 months", 
   "option": "hospital",
   "price_increment": "15.00"},
   {"id": 4, 
   "idd": "",
   "type": "PHARMACY",
   "option": "pharmacy",
    },
   {"id": 5, 
   "idd": "",
   "type": "CHEMIST",
   "option": "chemist",

  }]